server:
  servlet:
    contextPath: /mc
  port: 8000

spring:
  application:
    name: master-customer
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydb
    username: sa
    password: password  
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        enable_lazy_load_no_trans: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  h2:
    console:
      enabled: true